### ISSUE TITLE
Need som improvements to merge in lirc-remotes

### ISSUE THREAD

**Issue by leamas** [nokru/lg-ac-lirc#2]
Hi!

Seems I lost you message, talking this way instead.

Basically, this looks fine and would be great to merge. However:
- It would be better to use the output from irrecord -a, which is a much cleaner representation (but a test is of course needed)
- A photo of the device(preferablu ~100kb)
- Unless the buttons are marked exactly as the button names in the config we need some sort of explanation how the key names are mapped to physical buttons

**Comment by nokru** [comment]
hello @leamas sorry for the late reply, but it wasn't warm here until now and so i didn't had it up and running - i tried it again and as expected it's not able to record with irrecord -a - it says no gaps found - therefore i recorded it raw

will add the photo and the description of the buttons asap
